# Generated by Django 3.2.4 on 2021-06-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oinkerprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oinkerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
